// src/components/Navbar.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import { synthSound } from "../utils/audio";

  const dispatch = createEventDispatcher();
  export let activeTab: string = "home";
  export let xp: number = 360;
  export let username: string = "akrist";

  function handleNavigate(tab: string, event: Event) {
    event.preventDefault();
    synthSound.click();
    dispatch("navigate", { tab });
  }

  function handleKeyDown(tab: string, event: KeyboardEvent) {
    if (event.key === "Enter" || event.key === " ") {
      handleNavigate(tab, event);
    }
  }

  function handleLogout() {
    synthSound.click();
    dispatch("logout");
  }
</script>

<nav>
  <div
    class="logo"
    on:click={(e) => handleNavigate("home", e)}
    on:keydown={(e) => handleKeyDown("home", e)}
    role="link"
    tabindex="0"
  >
    <em>E</em>PHEMERAL
  </div>
  <div class="nav-mid">
    <a
      href="#home"
      class={activeTab === "home" ? "on" : ""}
      on:click={(e) => handleNavigate("home", e)}>Home</a
    >
    <a
      href="#blitz"
      class={activeTab === "series" ? "on" : ""}
      on:click={(e) => handleNavigate("series", e)}>Series</a
    >
    <a
      href="#leaderboard"
      class={activeTab === "leaderboard" ? "on" : ""}
      on:click={(e) => handleNavigate("leaderboard", e)}>Leaderboard</a
    >
  </div>
  <div class="nav-r">
    <span class="nav-status">
      <span class="nav-dot"></span>
      <span class="nav-uid">{username}</span>
    </span>
    <span
      style="font-size: 0.55rem; font-family: var(--mono); color: var(--paper); background: rgba(255,255,255,0.06); padding: 0.2rem 0.5rem; border: 1px solid rgba(255,255,255,0.1); display: flex; align-items: center; gap: 0.3rem;"
    >
      <span style="color: var(--crt)">⚡</span>
      <span id="nav-xp">{xp} XP</span>
    </span>
    <button class="nav-btn" on:click={handleLogout}>Logout</button>
  </div>
</nav>

// src/components/Navbar.tsx
import React from 'react';
import { synthSound } from '../utils/audio';

interface NavbarProps {
  activeTab: string;
  xp: number;
  username: string;
  onNavigate: (tab: string) => void;
  onLogout: () => void;
}

export const Navbar: React.FC<NavbarProps> = ({
  activeTab,
  xp,
  username,
  onNavigate,
  onLogout,
}) => {
  const handleNavigate = (tab: string, event: React.MouseEvent | React.KeyboardEvent) => {
    event.preventDefault();
    synthSound.click();
    onNavigate(tab);
  };

  const handleKeyDown = (tab: string, event: React.KeyboardEvent) => {
    if (event.key === 'Enter' || event.key === ' ') {
      handleNavigate(tab, event);
    }
  };

  const handleLogoutClick = () => {
    synthSound.click();
    onLogout();
  };

  return (
    <nav className="relative z-50 w-full flex items-center justify-between h-[56px] px-6 bg-[#06060e]/92 backdrop-blur-md border-b border-white/10 select-none">
      {/* Brand logo */}
      <div
        className="font-bebas text-lg font-black tracking-[0.18em] text-paper cursor-pointer flex items-center select-none outline-none focus:text-mg-acc"
        onClick={(e) => handleNavigate('home', e)}
        onKeyDown={(e) => handleKeyDown('home', e)}
        role="link"
        tabIndex={0}
      >
        <span className="text-mg-acc text-[1.25em]">B</span>INARY BEATS
      </div>

      {/* Navigation middle links */}
      <div className="flex items-center gap-1.5">
        <a
          href="#home"
          className={`font-mono text-[9px] tracking-widest uppercase py-1 px-3.5 border border-transparent transition-all duration-150 ${activeTab === 'home'
              ? 'text-mg-acc border-mg-acc bg-mg-acc/5 font-bold'
              : 'text-white/35 hover:text-white/60 hover:border-white/10 hover:bg-white/[0.02]'
            }`}
          onClick={(e) => handleNavigate('home', e)}
        >
          Home
        </a>

        <a
          href="#blitz"
          className={`font-mono text-[9px] tracking-widest uppercase py-1 px-3.5 border border-transparent transition-all duration-150 ${activeTab === 'blitz'
              ? 'text-mg-acc border-mg-acc bg-mg-acc/5 font-bold'
              : 'text-white/35 hover:text-white/60 hover:border-white/10 hover:bg-white/[0.02]'
            }`}
          onClick={(e) => handleNavigate('blitz', e)}
        >
          blitz
        </a>

        <a
          href="#leaderboard"
          className={`font-mono text-[9px] tracking-widest uppercase py-1 px-3.5 border border-transparent transition-all duration-150 ${activeTab === 'leaderboard'
              ? 'text-mg-acc border-mg-acc bg-mg-acc/5 font-bold'
              : 'text-white/35 hover:text-white/60 hover:border-white/10 hover:bg-white/[0.02]'
            }`}
          onClick={(e) => handleNavigate('leaderboard', e)}
        >
          Leaderboard
        </a>
      </div>

      {/* Right connection details & status */}
      <div className="flex items-center gap-4">
        <span className="flex items-center gap-1.5 font-mono text-[9px] tracking-wider text-white/35">
          <span className="w-1.5 h-1.5 rounded-full bg-crt animate-pulse"></span>
          <span className="font-semibold text-white/50">{username}</span>
        </span>

        <span className="font-mono text-[9px] text-paper bg-white/[0.03] px-2.5 py-1 border border-white/10 flex items-center gap-1.5">
          <span className="text-crt animate-pulse">⚡</span>
          <span className="font-bold">{xp} XP</span>
        </span>

        <button
          className="font-mono text-[9px] tracking-widest uppercase border border-white/15 bg-white/5 hover:border-mg-acc hover:text-mg-acc hover:bg-mg-acc/5 py-1 px-3 cursor-pointer transition-all duration-150 active:translate-y-[1px]"
          onClick={handleLogoutClick}
        >
          Logout
        </button>
      </div>
    </nav>
  );
};
